from typing import Optional

_DATABASE = [
    # ── FENTY BEAUTY ──────────────────────────────────────────────────────────
    {
        "brand": "Fenty Beauty",
        "shade_name": "110N",
        "shade_code": "110N",
        "undertone": "neutro",
        "fitzpatrick_range": [1, 2],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "120W",
        "shade_code": "120W",
        "undertone": "quente",
        "fitzpatrick_range": [1, 2],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "130C",
        "shade_code": "130C",
        "undertone": "frio",
        "fitzpatrick_range": [1, 2],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "230N",
        "shade_code": "230N",
        "undertone": "neutro",
        "fitzpatrick_range": [2, 3],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "240W",
        "shade_code": "240W",
        "undertone": "quente",
        "fitzpatrick_range": [2, 3],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "250C",
        "shade_code": "250C",
        "undertone": "frio",
        "fitzpatrick_range": [2, 3],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "330N",
        "shade_code": "330N",
        "undertone": "neutro",
        "fitzpatrick_range": [3, 4],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "340W",
        "shade_code": "340W",
        "undertone": "quente",
        "fitzpatrick_range": [3, 4],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "350C",
        "shade_code": "350C",
        "undertone": "frio",
        "fitzpatrick_range": [3, 4],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "430N",
        "shade_code": "430N",
        "undertone": "neutro",
        "fitzpatrick_range": [4, 5],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "440W",
        "shade_code": "440W",
        "undertone": "quente",
        "fitzpatrick_range": [4, 5],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "450C",
        "shade_code": "450C",
        "undertone": "frio",
        "fitzpatrick_range": [4, 5],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "490N",
        "shade_code": "490N",
        "undertone": "neutro",
        "fitzpatrick_range": [5, 6],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "495W",
        "shade_code": "495W",
        "undertone": "quente",
        "fitzpatrick_range": [5, 6],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },
    {
        "brand": "Fenty Beauty",
        "shade_name": "498C",
        "shade_code": "498C",
        "undertone": "frio",
        "fitzpatrick_range": [5, 6],
        "price_range": "$38–$42",
        "where_to_buy": "https://www.fentybeauty.com",
    },

    # ── MAC ───────────────────────────────────────────────────────────────────
    {
        "brand": "MAC",
        "shade_name": "NC10",
        "shade_code": "NC10",
        "undertone": "quente",
        "fitzpatrick_range": [1, 2],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NW10",
        "shade_code": "NW10",
        "undertone": "frio",
        "fitzpatrick_range": [1, 2],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "N3",
        "shade_code": "N3",
        "undertone": "neutro",
        "fitzpatrick_range": [1, 2],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NC20",
        "shade_code": "NC20",
        "undertone": "quente",
        "fitzpatrick_range": [2, 3],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NW20",
        "shade_code": "NW20",
        "undertone": "frio",
        "fitzpatrick_range": [2, 3],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "N4",
        "shade_code": "N4",
        "undertone": "neutro",
        "fitzpatrick_range": [2, 3],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NC35",
        "shade_code": "NC35",
        "undertone": "quente",
        "fitzpatrick_range": [3, 4],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NW35",
        "shade_code": "NW35",
        "undertone": "frio",
        "fitzpatrick_range": [3, 4],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "N5",
        "shade_code": "N5",
        "undertone": "neutro",
        "fitzpatrick_range": [3, 4],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NC45",
        "shade_code": "NC45",
        "undertone": "quente",
        "fitzpatrick_range": [4, 5],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NW45",
        "shade_code": "NW45",
        "undertone": "frio",
        "fitzpatrick_range": [4, 5],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NC50",
        "shade_code": "NC50",
        "undertone": "quente",
        "fitzpatrick_range": [5, 6],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "NW55",
        "shade_code": "NW55",
        "undertone": "frio",
        "fitzpatrick_range": [5, 6],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },
    {
        "brand": "MAC",
        "shade_name": "N7",
        "shade_code": "N7",
        "undertone": "neutro",
        "fitzpatrick_range": [5, 6],
        "price_range": "$35–$40",
        "where_to_buy": "https://www.maccosmetics.com",
    },

    # ── MAYBELLINE ────────────────────────────────────────────────────────────
    {
        "brand": "Maybelline",
        "shade_name": "110 Porcelain",
        "shade_code": "110",
        "undertone": "neutro",
        "fitzpatrick_range": [1, 2],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "115 Ivory",
        "shade_code": "115",
        "undertone": "quente",
        "fitzpatrick_range": [1, 2],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "120 Classic Ivory",
        "shade_code": "120",
        "undertone": "frio",
        "fitzpatrick_range": [1, 2],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "220 Natural Beige",
        "shade_code": "220",
        "undertone": "neutro",
        "fitzpatrick_range": [2, 3],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "230 Sand Beige",
        "shade_code": "230",
        "undertone": "quente",
        "fitzpatrick_range": [2, 3],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "240 Golden Beige",
        "shade_code": "240",
        "undertone": "frio",
        "fitzpatrick_range": [2, 3],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "310 Sun Beige",
        "shade_code": "310",
        "undertone": "neutro",
        "fitzpatrick_range": [3, 4],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "320 Warm Nude",
        "shade_code": "320",
        "undertone": "quente",
        "fitzpatrick_range": [3, 4],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "330 Toffee",
        "shade_code": "330",
        "undertone": "frio",
        "fitzpatrick_range": [3, 4],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "360 Mocha",
        "shade_code": "360",
        "undertone": "neutro",
        "fitzpatrick_range": [4, 5],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "370 Java",
        "shade_code": "370",
        "undertone": "quente",
        "fitzpatrick_range": [4, 5],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "380 Espresso",
        "shade_code": "380",
        "undertone": "frio",
        "fitzpatrick_range": [4, 5],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "395 Deep Espresso",
        "shade_code": "395",
        "undertone": "neutro",
        "fitzpatrick_range": [5, 6],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "397 Ebony",
        "shade_code": "397",
        "undertone": "quente",
        "fitzpatrick_range": [5, 6],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
    {
        "brand": "Maybelline",
        "shade_name": "399 Onyx",
        "shade_code": "399",
        "undertone": "frio",
        "fitzpatrick_range": [5, 6],
        "price_range": "$10–$14",
        "where_to_buy": "https://www.maybelline.com",
    },
]

# Fallback undertone priority when exact match unavailable
_UNDERTONE_FALLBACK = {
    "quente": ["quente", "neutro", "frio"],
    "frio":   ["frio",   "neutro", "quente"],
    "neutro": ["neutro", "quente", "frio"],
}


def get_recommendations(
    fitzpatrick: int,
    undertone: str,
    max_per_brand: int = 1,
) -> list[dict]:
    """Return up to max_per_brand shades per brand matching the skin profile."""
    results = []
    brands_seen: dict[str, int] = {}

    priority = _UNDERTONE_FALLBACK.get(undertone, ["neutro", "quente", "frio"])

    for preferred_undertone in priority:
        for shade in _DATABASE:
            lo, hi = shade["fitzpatrick_range"]
            if not (lo <= fitzpatrick <= hi):
                continue
            if shade["undertone"] != preferred_undertone:
                continue
            brand = shade["brand"]
            if brands_seen.get(brand, 0) >= max_per_brand:
                continue
            results.append({
                "brand":           shade["brand"],
                "shade_name":      shade["shade_name"],
                "shade_code":      shade["shade_code"],
                "undertone":       shade["undertone"],
                "fitzpatrick_range": shade["fitzpatrick_range"],
                "price_range":     shade["price_range"],
                "where_to_buy":    shade["where_to_buy"],
            })
            brands_seen[brand] = brands_seen.get(brand, 0) + 1

        # Stop as soon as every brand has a result
        if len(brands_seen) >= len({s["brand"] for s in _DATABASE}):
            break

    return results
